#!/bin/bash
# Build the DreamZero BYOC training image LOCALLY and push to the ECR repo
# created by the CDK stack. Reads the repo URI from pipeline/pipeline_config.json
# (generated by cdk/generate_pipeline_config.py).
#
# Prefer the stack's CodeBuild image factory instead (no local Docker, no
# ~18GB upload, and it publishes the digest-pinned URI to SSM):
#   aws codebuild start-build --project-name <project>-image-build \
#       --environment-variables-override name=IMAGE_TAG,value=v11,type=PLAINTEXT
# This script remains for offline iteration on the Dockerfile.
# Usage: bash build_and_push.sh [tag]   (default: v11)
set -euo pipefail

TAG=${1:-v11}
DLC_ACCOUNT=763104351884   # AWS public Deep Learning Containers registry

cd "$(dirname "$0")"
CFG=../pipeline/pipeline_config.json
[ -f "$CFG" ] || { echo "ERROR: $CFG not found — deploy the CDK stack and run cdk/generate_pipeline_config.py first"; exit 1; }

REPO_URI=$(python3 -c "import json; print(json.load(open('$CFG'))['ecr_repo_uri'])")
REGION=$(python3 -c "import json; print(json.load(open('$CFG'))['region'])")
PROFILE_ARG=$(python3 -c "import json; p=json.load(open('$CFG')).get('profile'); print(f'--profile {p}' if p else '')")

aws ecr get-login-password $PROFILE_ARG --region "$REGION" | \
    docker login --username AWS --password-stdin "$DLC_ACCOUNT.dkr.ecr.$REGION.amazonaws.com"
aws ecr get-login-password $PROFILE_ARG --region "$REGION" | \
    docker login --username AWS --password-stdin "${REPO_URI%%/*}"

# DLC_REGION keeps the Dockerfile's FROM registry in the same region we just
# logged into (the DLC account publishes identical images per region).
docker build --build-arg DLC_REGION="$REGION" -t "$REPO_URI:$TAG" .
docker push "$REPO_URI:$TAG"
echo "Pushed: $REPO_URI:$TAG"
